### ISSUE TITLE
Container always restarting

### ISSUE THREAD

**Issue by Darguima** [ChatDeBlofeld/seafile-arm-docker#10]
Hi,

I followed all the documentation (with No Swag) to run the Seafile Server.

After run `./compose.sh up -d` and access my Raspbery by its IP I only can see the nginx page. 

![image](https://user-images.githubusercontent.com/49988070/181357203-98b84cdb-cb21-419d-8377-ac70d1926dc2.png)

After check my containers I noticed that `mariadb` and `seafile` were always restarting:

```
$ docker container ls

CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                            PORTS                NAMES
0ea747509170   linuxserver/mariadb      "/init"                  40 minutes ago   Restarting (139) 5 seconds ago                         seafile-arm-docker_db_1
c3df51415171   franchetti/seafile-arm   "/docker_entrypoint.…"   40 minutes ago   Restarting (132) 59 seconds ago                        seafile-arm-docker_seafile_1
1eb757b21fe7   nginx                    "/docker-entrypoint.…"   40 minutes ago   Up 39 minutes                     0.0.0.0:80->80/tcp   seafile-arm-docker_reverse-proxy_1

```

Any ideia of what could be?

I have a Raspberry Pi Model B Rev 2, with an ARMv6. Could this old processor be the problem? If yes, is a way to run Seafile on it?

**Comment by ChatDeBlofeld** [comment]
>I have a Raspberry Pi Model B Rev 2, with an ARMv6. Could this old processor be the problem? If yes, is a way to run Seafile on it?

Hi,

Unfortunately, I think it can be related indeed. [Wikipedia](https://en.wikipedia.org/wiki/Raspberry_Pi#Raspberry_Pi) states the Pi2 has a armv7 or v8 SoC though, this is quite confusing.

You can check the logs with `docker logs <container id>` and if you see something like `exec format error` you'll know where you stand.

**Comment by Darguima** [comment]
> [Wikipedia](https://en.wikipedia.org/wiki/Raspberry_Pi#Raspberry_Pi) states the Pi2 has a armv7 or v8 SoC though, this is quite confusing.

I just copied the CPU info from the terminal command, so I believe that it's right:

```
$ cat /proc/cpuinfo

processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
...
Model           : Raspberry Pi Model B Rev 2
```

> You can check the logs with `docker logs <container id>` and if you see something like `exec format error` you'll know where you stand.

I also already tried it, but it desn't return anything:

```
$ docker logs 0ea747509170
$ docker logs c3df51415171
```

> Unfortunately, I think it can be related indeed.

So, if the problem is  the processor, do you know any way to setup Seafile on ARMv6?

**Comment by ChatDeBlofeld** [comment]
Woops, didn't realize it was a Pi first gen, don't know why I thought it was a 2.

Anyway, the only solution I see would be to build Seafile by yourself... which could be a bit cumbersome.

The community maintained [build script](https://github.com/haiwen/seafile-rpi) will install all required dependencies, compile the different parts and plumb everything together. It worth a try, you can launch it and cross your fingers.

```bash
$ wget https://raw.githubusercontent.com/haiwen/seafile-rpi/master/build.sh
$ chmod u+x build.sh
$ ./build.sh -DTA -v 9.0.6 \
      -h https://raw.githubusercontent.com/ChatDeBlofeld/seafile-arm-docker-base/v9.0.6/requirements/seahub.txt \
      -d https://raw.githubusercontent.com/ChatDeBlofeld/seafile-arm-docker-base/v9.0.6/requirements/seafdav.txt
```

**Comment by Darguima** [comment]
I had already tried the build script, but decided to try again with your command, and the same problem returned.

I deployed the server  following this [manual for MySQL](https://manual.seafile.com/deploy/using_mysql/).  Everything goes right, I could even run `./seafile.sh start` and `./seahub.sh start` without any error.

Seafile seems start and run without problems, but SeaHub after like 10 seconds stop and doesn't write any log. When I run `pgrep -f "seahub"` doesn't return anything.

```
$ `pgrep -f "seahub"`
$ cat /opt/seafile/logs/seahub.log
```
So again I can't run Seafile or even know why I can't it.

**Comment by ChatDeBlofeld** [comment]
Well, it's quite promising though. 

You should try to set `daemon` variable to `False` in `gunicorn.conf.py`. Then launch seahub again, if it crashes you'll see the stack trace.

**Comment by Darguima** [comment]
Solved!!

So after set `daemon` to `False`, when I run `SeaHub` I start receive the Python Pillow Library error:

```
$ /opt/seafile/seafile-server-latest/seahub.sh start

LC_ALL is not set in ENV, set to en_US.UTF-8
/opt/seafile/seafile-server-latest/seahub.sh: line 228: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Starting seahub at port 8000 ...
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-9.0.6/seahub/seahub/avatar/models.py", line 23, in <module>
    from PIL import Image
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-9.0.6/seahub/seahub/wsgi.py", line 25, in <module>
    application = get_wsgi_application()
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/seafile/seafile-server-9.0.6/seahub/thirdpart/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-9.0.6/seahub/seahub/avatar/models.py", line 26, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'
Error:Seahub failed to start.
Please try to run "./seahub.sh start" again
```
I focused on 

```
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
```
And  with a quick search find this [Stackoverflow Post](https://stackoverflow.com/questions/48012582/pillow-libopenjp2-so-7-cannot-open-shared-object-file-no-such-file-or-directo):

```
$ sudo apt-get install libopenjp2-7
```

I already tested most parte of Seafile's features and it seems work properly, so thank you so much
